name: teledintistry
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 3.0.1
  persistent_bottom_nav_bar: 4.0.2
  flutter_gallery_3d: ^1.0.4
  intl: ^0.17.0
  firebase_auth: 3.4.2
  firebase_core: 1.21.1
  cloud_firestore: 3.4.6
  firebase_storage: 10.3.7
  cached_network_image: 3.2.0
  flutter_document_picker: 5.1.0
  emoji_picker_flutter: 1.3.0
  flutter_pdfview: 1.2.0
  dio: 4.0.6
  path_provider: 2.0.11
  open_file: 3.2.1
  advance_pdf_viewer: 2.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/default_odontogram/
    - assets/odontogram/
  uses-material-design: true

